// DO NOT EDIT THIS FILE.
// IT IS GENERATED BY WPT

// Check "lib/Server.js" for your own code.

// This file is entry point for node.js hosting providers
// so it must be on this path

var path = require("path");

var Server = require("./lib/Server");
var stats = require("./publishedStats.json");

var server = new Server({
	publishedStats: stats,
	publicPath: path.join(__dirname, "public"),
	indexHtml: require("fs").readFileSync(path.join(__dirname, "index.html"), "utf-8")
});

// TODO add Watcher here and issue server.updateOptions(...)

server.listen(process.env.NODE_PORT || 8080);