// DO NOT EDIT THIS FILE.
// IT IS GENERATED BY WPT

// Check "lib/Server.js" for your own code.

// This file is entry point for node.js hosting providers
// so it must be on this path

var path = require("path");

var er = require("enhanced-require")(module, require("./_template/loadOptions")("enhancedRequire", "Production"));

var Server = er("./app/lib/Server");
var stats = er("./publishedStats.json");

var server = new Server({
	publishedStats: stats,
	publicPath: path.join(__dirname, "public")
});

// TODO add Watcher here and issue server.updateOptions(...)

server.listen(process.env.NODE_PORT || 8080);